# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  dv_img_config = debug
endif
ifeq ($(config),release)
  dv_img_config = release
endif

PROJECTS := dv_img

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

dv_img:
ifneq (,$(dv_img_config))
	@echo "==== Building dv_img ($(dv_img_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(dv_img_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   dv_img"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"